import {
  Anchor,
  BadgeCheck,
  Cable,
  CircleDot,
  CircleSlash,
  ClipboardCheck,
  ClipboardPaste,
  Columns3,
  Copy,
  CopyPlus,
  Cpu,
  Cylinder,
  Diamond,
  Download,
  Droplet,
  FileInput,
  FlipHorizontal2,
  Folder,
  FolderOpen,
  GitBranch,
  GitCommitHorizontal,
  GitMerge,
  Split,
  Keyboard,
  Layers,
  List,
  ListChecks,
  Lock,
  Maximize,
  Minus,
  MoreHorizontal,
  Package,
  Palette,
  PanelRight,
  Pencil,
  Plus,
  Redo2,
  RotateCcw,
  Ruler,
  Scissors,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  StickyNote,
  SunMoon,
  Table,
  Tag,
  Trash2,
  Triangle,
  Undo2,
  Waves,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  anchor: Anchor,
  "badge-check": BadgeCheck,
  cable: Cable,
  "circle-dot": CircleDot,
  "circle-slash": CircleSlash,
  "clipboard-check": ClipboardCheck,
  "clipboard-paste": ClipboardPaste,
  columns: Columns3,
  copy: Copy,
  "copy-plus": CopyPlus,
  cpu: Cpu,
  cylinder: Cylinder,
  scissors: Scissors,
  diamond: Diamond,
  download: Download,
  droplet: Droplet,
  "file-input": FileInput,
  "flip-horizontal": FlipHorizontal2,
  folder: Folder,
  "folder-open": FolderOpen,
  "git-commit": GitCommitHorizontal,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  split: Split,
  keyboard: Keyboard,
  layers: Layers,
  list: List,
  "list-checks": ListChecks,
  lock: Lock,
  maximize: Maximize,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  package: Package,
  palette: Palette,
  "panel-right": PanelRight,
  pencil: Pencil,
  plus: Plus,
  redo: Redo2,
  "rotate-ccw": RotateCcw,
  ruler: Ruler,
  search: Search,
  settings: Settings,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  "sticky-note": StickyNote,
  "sun-moon": SunMoon,
  table: Table,
  tag: Tag,
  "trash-2": Trash2,
  triangle: Triangle,
  undo: Undo2,
  waves: Waves,
};

export function Icon({ name, size = 16 }: { name?: string; size?: number }) {
  const C = name ? MAP[name] : undefined;
  return C ? <C size={size} strokeWidth={1.5} /> : null;
}
